plugins:
  - {name: obstacle_local,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_local,           type: "costmap_2d::InflationLayer"}
  - {name: voxel_local,           type: "costmap_2d::InflationLayer"}

# SLAM_local:
#   map_topic: "/map"
#   first_map_only: false
#   lethal_cost_threshold: 50

obstacle_local:
  observation_sources: "lidar"
  lidar:
    topic: "/velodyne_points"
    # topic: "/os_cloud_node/points"
    # sensor_frame: "h2/velodyne"
    data_type: "PointCloud2"
    observation_persistence: 0.0
    expected_update_rate: 2.0 # seconds timeout
    marking: true
    clearing: true
    max_obstacle_height: 1.3
    min_obstacle_height: 0.2
    obstacle_range: 5
    raytrace_range: 5


inflation_local:
  inflation_radius: 0.2
  cost_scaling_factor: 1.0


voxel_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 10
  unknown_threshold: 0
  #mark_threshold: 2
  publish_voxel_map: true
  combination_method: 1
  observation_sources: velodyne
  output_points:
    data_type: PointCloud2
    topic: /output_points
    marking: true
    clearing: true
    obstacle_range: 1.90
    raytrace_range: 2.00
    min_obstacle_height: 0.00
    max_obstacle_height: 3.00
    mark_threshold: 3