footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.02

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 5.0
max_obstacle_height: 1.5
min_obstacle_height: 0.1

# global_frame: map
# rolling_window: true
# always_send_full_costmap: true
# static_map: false
# map_type: costmap

